### ISSUE TITLE
2.13 - Cutting problem when creating a path snapped at both ends

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1655]
In Geotrek-admin 2.13.0, I just made some tests and when creating a new path that is snapped to existing path at both ends, most of the time only one the existing paths is cut. 
It cuts at only one of both snapped ends of the new paths. 

Not sure if this is part of what was fixed in 2.14.1 ?
Nor about other PATH SPLITTING issues : https://github.com/GeotrekCE/Geotrek-admin/search?q=split&type=Issues&utf8=%E2%9C%93

**Comment by submarcos** [comment]
There is a 'bug' in postgis. Sometimes it doesn't see intersections at ends. I fixed that with particular code in a PR. #1666 (need some tests)
Leaflet has its own snapping in pixels, and database its own in meters. It is possible that leaflet show always a path as snapped, but distance is so great to be snapped. (Bug reproduce on my instance, leaflet see path snapped because < 30pixels, but database doesn't because there is 4,5m of distance.)
You can reduce leaflet snapping pixel (SNAP_DISTANCE) and increase database snapping meters (PATH_SNAPPING_DISTANCE) in settings to fix that as well.

**Comment by camillemonchicourt** [comment]
OK thanks !

**Comment by camillemonchicourt** [comment]
Yes, tested again on 2.18.3 and got no problem.
