### ISSUE TITLE
Update and pg_dump

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1675]
When you update your Geotrek-admin version with ``install.sh``, you are invited to backup your database. 

I just saw in PNRV installation log file that there can be a problem with pg_dump version : 

```
pg_dump: version du serveur : 9.4.13 ; pg_dump version : 9.3.4
pg_dump: annulation à cause de la différence des versions
```

**Comment by submarcos** [comment]
there are two way to install geotrek, with local database and with external database. After editing etc/settings.ini, install.sh determines which packages to install. If it's local database, pg_dump version matches with postgresql-server version. Else, it depends on postgresql-server version installed and pg_dump version (not the same on 12.04 / 14.04 / 16.04)

According to last postgresql (we cant use JSON fields because ubuntu 12.04 default pgsql haven't) and POSTGIS versions (many deprecation warning on geotrek code in last version), I think it will be better to check postgresql and postgis version to allow upgrading Geotrek, before DB backup. In fact, with postgresql official APT repositery, we could control which pg_dump version we want or need to use. 

And say to user he needs to upgrade its PG and PostGIS versions before continue.

Some reflection and developments are required.

**Comment by submarcos** [comment]
There is a thinking about that. In external database install, there is not verification to check if versions match. Anyway, backward compatibilities (ubuntu 12.04 -> pg 9.1 postgis 2.0, ubuntu 14.04 -> 9.3 postgios 2.1, ubuntu 16.04 -> 9.5 postgis 2.2) 

I think it will be better to check postgresql and postgis installed version, and install good pg_dump version with postgresql apt official repository. In case of PG or PostGIS upgrade needed, we could say to user to upgrade its database before continue.

**Comment by gutard** [comment]
PNRV seems tu use Debian instead of Ubuntu. This is not officially supported.
Postgresql 9.3 and 9.4 are installed in parallel. This means a major upgrade was done and not completed.

**Comment by camillemonchicourt** [comment]
OK I understand!

**Comment by camillemonchicourt** [comment]
External databases is a specific installation not covered by automatic install.
We are not compatible with Ubuntu 12 in latest versions so it is good so.
