### ISSUE TITLE
Fusing path and trails

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1723]
When fusing 2 paths that are related to the same trail, the resulting paths is linked twice to the trail : 

![trails-fused](https://user-images.githubusercontent.com/4418840/38143852-9e929254-3442-11e8-8261-8290c5ca1ce2.jpg)

**Comment by camillemonchicourt** [comment]
Same for interventions that are doubled after fusing some paths : 

![interventions](https://user-images.githubusercontent.com/4418840/38151344-0ff13034-3463-11e8-82e6-39eb575caa43.jpg)

**Comment by LePetitTim** [comment]
I checked it and it happens only with treks. It's still not fixed.

**Comment by LePetitTim** [comment]
I couldn't reproduce the bug with intervention but for treks i did. I am trying to find a solution for this.

**Comment by LePetitTim** [comment]
Actually it's normal to have this behaviour. 

We imagine this case : 
               A---------------B + C-------------------D         A-----------------BC----------------D
                       |---------------------|                                         |------------------|
                       E1                                                                E1
AB and CD are 2 paths
E1 is the combination of : (start_point : 0.5, end_point : 1) for path AB and (start_point : 0, end_point : 0.5) for path CD.
When the merge is done we got : 2 aggregation for the same path : (start_point:0.25, end_point: 0.5) and (start_point: 0.5, end_point: 0.75) for AD
So yes we have 2 intervention/ treks and all linear information, 2 times because the aggregation is made like this.

Why do we not merge this aggregation : 
- We loose the information when there is a trek going in the same path 2 times. We want to keep the information when we turn back.

Solution :
Deplace the path and it will update everything !

**Comment by camillemonchicourt** [comment]
Hum OK, I think I understand. Btu we cant move each path after fusing them. 
Will think about it. 
Thanks for testing.

**Comment by LePetitTim** [comment]
Deplace the topology* sorry ! (trek, intervention)
