### ISSUE TITLE
NGINX overriding lost at each update

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1878]
At each Geotrek-admin version update, its global NGINX conf is totally regenerated in file ``/etc/nginx/sites-available/geotrek``.

In order to override and customise this NGINX conf, there is a file in Geotrek-folder to do that : ``/home/<myuser>/Geotrek-admin/etc/nginx.d/inc.conf``.

This file is copied into the new Geotrek-admin version during update processs (https://geotrek.readthedocs.io/en/master/installation.html#software-update) with the command : ``cp -aR ../previous-version/etc/ .``.

But after updating Geotrek-admin, the content of this file is lost, certainly during ``install.sh`` ?

Its content shouldn't be lost when updating Geotrek-admin.

**Comment by Cynthia-Borot-PNE** [comment]
What english level ! 



		Cynthia BOROT 
Chargée de mission GEOTREK et Outdoor Data 
Incaricata di missione GEOTREK e Outdoor Data 

Parc national des Écrins 
Tél : +33 (0)4 92 40 20 27 
[ http://www.ecrins-parcnational.fr/ | www.ecrins-parcnational.fr ] 


De: "Camille Monchicourt" <notifications@github.com> 
À: "GeotrekCE/Geotrek-admin" <Geotrek-admin@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Samedi 2 Mars 2019 09:16:04 
Objet: [GeotrekCE/Geotrek-admin] NGINX overriding lost at each update (#1878) 



At each Geotrek-admin version update, its global NGINX conf is totally regenerated in file /etc/nginx/sites-available/geotrek . 

In order to override and customise this NGINX conf, there is a file in Geotrek-folder to do that : /home/<myuser>/Geotrek-admin/etc/nginx.d/inc.conf . 

This file is copied into the new Geotrek-admin version during update processs ( [ https://geotrek.readthedocs.io/en/master/installation.html#software-update | https://geotrek.readthedocs.io/en/master/installation.html#software-update ] ) with the command : cp -aR ../previous-version/etc/ . . 

But after updating Geotrek-admin, the content of this file is lost, certainly during install.sh ? 

Its content shouldn't be lost when updating Geotrek-admin.

**Comment by gutard** [comment]
Désormais, le fichier de conf nginx est généré à partir du template /opt/geotrek-admin/var/conf/nginx.conf.in qu'il est possible de modifier. L'en-tête du fichier geotrek.conf contient un avertissement.
