### ISSUE TITLE
Can't see the minimum and maximum elevation

### ISSUE THREAD

**Issue by gzileni** [GeotrekCE/Geotrek-admin#3288]
When I enter a new path I cannot see the minimum and maximum elevation.

<img width="1778" alt="Schermata 2022-10-10 alle 12 03 45" src="https://user-images.githubusercontent.com/6775950/194843302-917e794f-c5f1-45b9-a551-40364aecd48a.png">

In the database table core_path fields min_elevation and max_elevation are always equals to Zero.

<img width="846" alt="Schermata 2022-10-10 alle 12 05 57" src="https://user-images.githubusercontent.com/6775950/194843366-ee9ed32e-b59a-42d4-b2c2-e725b38491ec.png">

**Comment by babastienne** [comment]
Hi, thanks for your interest into Geotrek.

In order to compute elevation, Geotrek need to have a raster in the database that should cover all your territory.
You can add this DEM by using the command `loaddem`

You can find more information about this command here : https://geotrek.readthedocs.io/en/2.87.2/install/loading-data.html#load-mnt-raster
