### ISSUE TITLE
Calls on non existent API route should return a JSON error

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#3492]
Currently a call on non-existent API route returns a web page with the error 404 template used in the user interface of Geotrek Admin. (i.e. it may have the tab opened by the session user, it has javascript, ...).

IMO it should return a simple JSON error with a message: "the route XXX was not found".

To reproduce : `curl --include -H "Accept:application/json" https://demo-admin.geotrek.fr/api/v2/doesnotexist`

**Comment by submarcos** [comment]
We cannot override django routing only in api sub endpoints. If route doesn't exists, reverse proxy or django manage 404 error and it's normal.

But mapentity 404 management cause problems by accessing explicit 404 in API details view. (ex: /api/v2/trek/xxx/) instead of returning JSON {"detail": "not found"}, it returns mapentity default view as described. and it's a problem for API design and compliance with swagger description

**Comment by babastienne** [comment]
Fix in #3656
