### ISSUE TITLE
Force 3D for geometries on insert/update in Paths table

### ISSUE THREAD

**Issue by leplatrem** [GeotrekCE/Geotrek-admin#688]
Would allow editions via QGis for example

**Comment by tudorbarascu** [comment]
I also just stumbled into the problem you described and I also noticed that `adding a trigger BEFORE INSERT/UPDATE has no effect, since verification is done sooner.` However, I found out that it is possible to build the 3d geometry with triggers if the geometry column wasn't added using type modifier (http://postgis.net/docs/AddGeometryColumn.html).
So, if you add create the geometry column using something like `SELECT AddGeometryColumn ('schema_name','table_name','geometry_column',SRID,'LINESTRING',3, false);` you can rework the geometry with triggers without the `ERROR:  Column has Z dimension but geometry does not`.
Thus, you can get away without a 2d geometry column.

**Comment by camillemonchicourt** [comment]
Thanks

**Comment by leplatrem** [comment]
Hi Tudor! 
If I'm not wrong, it's the first we see you here!
Do you use actually use Geotrek or you found our thread looking for the QGIS error ?
Thanks for your tips!

**Comment by tudorbarascu** [comment]
Hi Mathieu!
It is the the first time I'm seen here as I'm not a Geotrek user although I have visited the repository these last few months by searching for django and GIS stuff.
As you suspected, I found this thread by investigating the same error while using QGIS/Postgis and as I couldn't find any posted solutions I though that posting mine could help others in the future at least.
Thanks also for your nice repo!
